export interface IBaseStyle {
	opacity: number;
	zIndex: number;
	color: string;
	fontSize: string;
	whiteSpace: string;
	fontFamily: string;
	position: string;
	top: string;
	left: string;
	width: string;
	height: string;
	lineHeight: string;
	textDecoration: string;
	bold: string;
	backgroundColor: string;
	backgroundImage: string;
	borderRadius: string;
	backgroundSize: string;
	marginTop: string;
	borderColor: string;
	borderWidth: string;
	borderStyle: string;
	boxShadow: string;
	textAlign: string;
	overflow: string;
	textStrokeWidth?: string;
	textStrokeColor?: string;
}
